name: project1-grading
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.1
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - scikit-learn=1.1.2
  - pytest=7.1.2
  - gitpython=3.1.18
  - black=22.6.0
  - pytest-mock=3.7.0
